---

- name: "Create /var/ansible-openstack"
  file:
    path: "{{ files_directory }}"
    state: directory
    mode: '0755'

- name: "Download cirros image"
  get_url:
    url: http://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img
    dest: "{{ files_directory }}/cirros.img"

- name: "Install qemu-utils for qemu-img"
  apt:
    name: qemu-utils

- name: "Create cirros raw file"
  shell:
    cmd: >
      qemu-img convert -f qcow2 -O raw
      {{ files_directory }}/cirros.img {{ files_directory }}/cirros.raw
    creates: /var/ansible-openstack/cirros.raw
