---

# Create a user but don't update password if user exists

# Create a user but don't update password if user exists
- name: "Create the user 'DemoUser' in keystone"
  os_user:
    auth: "{{ openstack_auth }}"
    state: present
    name: DemoUser
    password: Breqwatr2019
    update_password: on_create
    email: demouser@example.com
    domain: default
    default_project: DemoProject
